### PR TITLE
Using correct schema protocol for test with auto TLS #329

### PR DESCRIPTION
**Pull request by rigazilla**
This PR select the correct schema protocol (http or https) for testing.
If infinispan.spec.security.endpointencryption.type is not null https is selected.

### CODE REVIEW

**Comment by dmvolod** [comment]
@rigazilla I tried this test on OCP 4.3, but TestClusterFormation still keep PersistentVolumeClaim and didn't pass.
test-cluster-formation-test-cluster-formation-0   Bound     pvc-6122c5de-efca-4fb8-bf46-5cdeaa05fd89
test-cluster-formation-test-cluster-formation-1   Bound     pvc-047434c8-8367-4af4-833f-d1f0dd7756d3
[dvolodin@dvolodin manager]$ oc get infinispan
No resources found.
That is strange, as this test passes on travis.

**Comment by rigazilla** [comment]
@dmvolod I don't think it's related to this PR. How does the test fail?
Can you check if the infinispan resource has the "finalizer.infinispan.org" in the metadata.finalizers?

**Comment by dmvolod** [comment]
Yes, sure, not to this PR. I will check, but block this PR test, however may be problem with my env also.

**Comment by dmvolod** [comment]
Oh, I've found regression in #315 , it creates a finalizer to often, if someone happens with external service creating, it has never reached finalizer, but already require it, as StatefulSet already present and PVC need to be finalized. @rigazilla please pay attention to this issue.

**Comment by rigazilla** [comment]
merged thanks!

**Pull request merged**
