### PR TITLE
ISPN-11787 issue 387 update manual install docs

### PR DESCRIPTION
**Pull request by oraNod**
https://issues.redhat.com/browse/ISPN-11787

### CODE REVIEW

**Comment by rigazilla** [comment]
@oraNod I can't remember, do we publish versioned docu? master(2.0.x) and 1.1.x?

**Comment by oraNod** [comment]
> @oraNod I can't remember, do we publish versioned docu? master(2.0.x) and 1.1.x?

@rigazilla hmmm. yeah, good point. right now we publish only master to infinispan.org. do you think we should start publishing versioned docu?

**Comment by rigazilla** [comment]
> > @oraNod I can't remember, do we publish versioned docu? master(2.0.x) and 1.1.x?
> 
> @rigazilla hmmm. yeah, good point. right now we publish only master to infinispan.org. do you think we should start publishing versioned docu?

yeah we probably need it, at least separated doc for 2.x and 1.x branches

**Comment by rigazilla** [comment]
merged thanks!

**Pull request merged**
