### PR TITLE
Tests should evaluates for cluster is wellFormed

### PR DESCRIPTION
**Pull request by dmvolod**

### CODE REVIEW

**Comment by ryanemerson** [comment]
@dmvolod The change makes sense :+1:. Can you add these checks to `backup_restore_test.go`?

**Comment by dmvolod** [comment]
> @dmvolod The change makes sense . Can you add these checks to `backup_restore_test.go`?

@ryanemerson it seems to Backup/Restore controller do this itself and we don't need to add additional validation

**Comment by ryanemerson** [comment]
> @ryanemerson it seems to Backup/Restore controller do this itself and we don't need to add additional validation

Good point! I had forgot about that :smile:

**Review by ryanemerson — APPROVED** [review]

**Review by rigazilla — APPROVED** [review]

**Comment by ryanemerson** [comment]
Thanks @dmvolod

**Pull request merged**
