### PR TITLE
Use OwnerReferences for PVC cleanup

### PR DESCRIPTION
**Pull request by dmvolod**

### CODE REVIEW

**Comment by rigazilla** [comment]
@dmvolod I think that this is the right way to deal with PVC cleanup. Also it prevents finalizer related troubles as in #412 
Please provide a definitive PR, thanks!!!

**Comment by dmvolod** [comment]
Thanks for feedback, @rigazilla 
I will create a backport to the 1.1.x after full review and possible feedback from others.

**Comment by dmvolod** [comment]
Waiting on feedback from @Crumby and PR #380 to be merged

**Comment by dmvolod** [comment]
@rigazilla could you please to merge this fix and I will backport it to 1.1.x and got feedback on test stage. Thank you.

**Comment by rigazilla** [comment]
merged, thanks @dmvolod !

**Pull request merged**
