### PR TITLE
Added Jenkinsfile

### PR DESCRIPTION
**Pull request by rigazilla**
Trivial PR adding the Jenkinsfile

### CODE REVIEW

**Comment by rigazilla** [comment]
This PR adds the Jenkinsfile for the release and the operatorhub PRs.
The pipeline that runs it is here: [pipeline](https://ci.infinispan.org/job/Operator%20Release/)
@galderz can you try a run?
There are two checkboxes:

- dryRun (runs everything but produce nothing... just for debugging)
- noPr (runs everything but doesn't create the pull request for operatorhub)

If you set **dryRun=false** and **noPr=true** you have all the branches and tags available for the inspection. Branches for the operatorhub PRs are created on my fork atm: [community-operators](https://github.com/rigazilla/community-operators).

I've used release number range 0.0.x for devs and testing

if you feel bold :) you can also try a full release with noPr=false

**Comment by rigazilla** [comment]
related to #152

**Comment by galderz** [comment]
@rigazilla Looks good. Just one question: should the github username be made a build parameter? It is unless `infinispan` org forks community-operators and we use that as fork for changes.

**Comment by rigazilla** [comment]
Yeah @galderz the idea was eventually to use `infinispan` user. But can be parametrized for now.

**Pull request merged**
