### PR TITLE
Rename Gossip Router deployment name

### PR DESCRIPTION
**Pull request by pruivo**
* "router pod" sound better instead of "tunnel pod"

### CODE REVIEW

**Review by ryanemerson — APPROVED** [review]
Changes are fine by me. Just waiting on another CI run as the xsite tests failed on the last one

**Comment by ryanemerson** [comment]
@pruivo On an upgrade won't this leave the old `-tunnel` deployment orphaned? What will the consequences be if there's both the old and new deployment running concurrently?

**Comment by pruivo** [comment]
I'm not sure but I would say yes.
Is there any function to perform deployments renaming?

**Comment by pruivo** [comment]
@ryanemerson added code to remove the old deployment.

**Comment by ryanemerson** [comment]
> Is there any function to perform deployments renaming?

Not that I'm aware of. I think the code you've added is the best we can do.

**Comment by ryanemerson** [comment]
Thanks @pruivo

**Pull request merged**
