### PR TITLE
Missied deletecollection resources for ingresses and routes

### PR DESCRIPTION
**Pull request by dmvolod**

### CODE REVIEW

**Comment by dmvolod** [comment]
@rigazilla could you please to have a look at this PR and merge it. I've missed some role permissions for list route and ingress deletion.

**Comment by rigazilla** [comment]
@dmvolod looks fine to me.
I was not able to find a description tough, could you add some details on what's failing without this?

**Review by rigazilla — APPROVED** [review]
LGTM

**Comment by rigazilla** [comment]
merged, thanks @dmvolod

**Pull request merged**
