### PR TITLE
Convert golang e2e test to unit tests

### PR DESCRIPTION
**Pull request by dmvolod**

### CODE REVIEW

**Comment by galderz** [comment]
Great start @dmvolod! Keep it up, can't wait to see all the rest of tests ported and make the testsuite lightning fast :)

**Comment by dmvolod** [comment]
@galderz , @rigazilla , @Crumby could you please to look at this tests
Other cases look like requires Kubernetes real REST server for tests

**Comment by galderz** [comment]
Hey @dmvolod, sorry we didn't get back on this. Are you working further on this?

**Comment by dmvolod** [comment]
Yes, @galderz working on it. I removed this branch, as manual rebase to difficult as infinispan_controller.go changed a lot. I will create a new one based on the new merged master.

**Pull request closed without merging**
