### PR TITLE
Print version at startup

### PR DESCRIPTION
**Pull request by rigazilla**

### CODE REVIEW

**Comment by dmvolod** [comment]
@rigazilla this was already implemented in master. Please cherry-pick required commit

**Comment by rigazilla** [comment]
@dmvolod uh yes. I though it was after the SDK upgrade

**Comment by rigazilla** [comment]
@dmvolod should be ok now. please a quick check :)

**Comment by dmvolod** [comment]
Looks good, thanks.

**Comment by rigazilla** [comment]
merged

**Pull request merged**
