### PR TITLE
Split main_test.go into separate files

### LINKED ISSUE #1117: Split main E2E testsuite
**Issue:** There is currently more then 20 tests running different deployments in main e2e test suite. When executing all the tests outside of CI (eg. OpenShift certification) any test failure will immediately halt rest of the test execution. With that many tests in single test file it's hard to tell which were executed and re-execute only those that were not.

**Proposal:** Split the main e2e test suite in several, logically grouped tests.

It'd be ideal if golang wouldn't halt test execution on failure but I haven't find a way to achieve this behavior yet.

### PR DESCRIPTION
**Pull request by Crumby**
Resolves #1117 by splitting tests in the `main_test.go` file in separate `*_test.go` files grouped by feature topic.

### CODE REVIEW

**Comment by ryanemerson** [comment]
@Crumby What's the command required to execute the different category of test?

**Comment by Crumby** [comment]
@ryanemerson TBH I'm not sure that's reasonably possible in our case. Theoretically it should be achievable by running `go test test/e2e/main/${group}_test.go` but I haven't tried it out and might not work in our case due to need of having `setup_test.go` which contains `TestMain()`. Also go doesn't see multiple files, it only sees functions, vars, etc. as if all the tests were in the single file (thus it's possible to have `TestMain()` and `testKube` in separate file and it works nicely).

I would say that best should would be with `-run ${regex}` option and some convention in test naming.

**Comment by ryanemerson** [comment]
@Crumby I thought the idea was to utilise build tags once the tests has been separated out into different files? https://github.com/infinispan/infinispan-operator/issues/1381

**Comment by Crumby** [comment]
@ryanemerson This PR is addressing #1117 only and the changes are purely cosmetic. The idea here is to improve navigation between tests and visibility in what is being testing in relation to a particular feature rather then having big single test file.

> I thought the idea was to utilise build tags once the tests has been separated out into different files? https://github.com/infinispan/infinispan-operator/issues/1381

I'll address #1381 in the different PR with a bit different more flexible solution that the build tags provide.

**Comment by ryanemerson** [comment]
Thanks @Crumby

**Pull request merged**
