### PR TITLE
#44 configurable credential for authentication

### PR DESCRIPTION
**Pull request by rigazilla**

### CODE REVIEW

**Comment by rigazilla** [comment]
Uh no, my mistake. I didn't notice that git detected a file rename, my idea is to have two different yaml files.

**Comment by rigazilla** [comment]
@galderz updated to address: https://github.com/infinispan/infinispan-operator/pull/46#discussion_r288644429

**Comment by galderz** [comment]
Looks good, integrating.

**Comment by galderz** [comment]
Oh bugger, merged without squashing commits. @rigazilla Can you make sure you squash your commits  when the PRs are ready? Thx :)

**Pull request merged**
