### PR TITLE
Check err and validate that issue #312 runs on k8s & ocp

### PR DESCRIPTION
**Pull request by dmvolod**

### CODE REVIEW

**Comment by Crumby** [comment]
@dmvolod @rigazilla Can we make this one priority and backport it to 1.1.x?

**Comment by dmvolod** [comment]
@Crumby , @rigazilla i'm not sure that we need to backport this to the 1.1.x as we don't have an updated Operator SDK version 0.15.2 there

**Comment by Crumby** [comment]
@dmvolod Makes sense. It doesn't. I haven't realized that.

**Comment by rigazilla** [comment]
@dmvolod can you check the failure in CI?

I think I can merge this. If there are no conflict I can port on 1.1.x also to keep branches closer. Ok?

**Comment by dmvolod** [comment]
Thanks, @rigazilla , add some fixes and waiting for CI completion.

**Comment by dmvolod** [comment]
@rigazilla this is ready for merging
We don't need to port it to the 1.1.x as this branch using o old SDK

**Comment by rigazilla** [comment]
> @rigazilla this is ready for merging
> We don't need to port it to the 1.1.x as this branch using o old SDK

I know it's not needed but If it works on 1.1.x and doesn't generate conflicts I would do the port to reduce the differences between branches and ease the subsequent backports

**Comment by dmvolod** [comment]
Oh, thanks,  @rigazilla  didn't think about it.
Let's merge this PR and i will create a PR for 1.1.x

**Comment by rigazilla** [comment]
merged, thanks @dmvolod !

**Pull request merged**
