### PR TITLE
Allow the user to define annotations for created resources #1423

### PR DESCRIPTION
**Pull request by ryanemerson**
The removal of `controllers/labels.go` is not strictly necessary for this feature, however it allows common functionality to be shared between controllers without having to rely on package wide functions. This is beneficial for when controller functionality starts to move from the `controllers` package in future refactoring PRs.

@oraNod Documentation is required for this feature. From a user perspective, adding custom annotations is the same as [adding labels](https://infinispan.org/docs/infinispan-operator/main/operator.html#adding-custom-labels_services). It can be achieved via env variables or annotations on the Infinispan cr.

ENV vars:

```
# Pods
INFINISPAN_OPERATOR_POD_TARGET_ANNOTATIONS

# Services
INFINISPAN_OPERATOR_TARGET_ANNOTATIONS
```

Annotations:

```
# Pods
infinispan.org/podTargetAnnotations: ...
# Services
infinispan.org/targetAnnotations: ...
```

### CODE REVIEW

**Comment by oraNod** [comment]
@ryanemerson Will the env vars be available for use downstream? Currently the publisher labels are community only.

**Comment by oraNod** [comment]
actually I think I've answered my own question. I don't believe the operator yaml is available downstream so the env vars for annotations should be community only. I could well be mistaken though. docs PR at: https://github.com/ryanemerson/infinispan-operator/pull/1

**Comment by ryanemerson** [comment]
@oraNod Env vars can be configured downstream and upstream  via the OLM Subscription. There's no need to install via yaml

https://access.redhat.com/solutions/5761251

**Review by oraNod — APPROVED** [review]
@ryanemerson Pushed a doc commit. Give me a shout if any other changes are needed. Nice work!

**Comment by ryanemerson** [comment]
Thanks @oraNod, the docs LGTM

**Review by rigazilla — APPROVED** [review]
LGTM!

**Pull request merged**
