### PR TITLE
Fix update regression from #684 with reflect.DeepEqual

### PR DESCRIPTION
**Pull request by dmvolod**
@rigazilla probably all potential update errors are fixed

### CODE REVIEW

**Comment by dmvolod** [comment]
@rigazilla added description to the `UpdateFn` and `ValidateFn` about mutations. Please review

**Review by rigazilla — COMMENTED** [review]
@dmvolod logs looks very clean now, no more update error.
I've added a commit with some optimizations:
- removed event requeue if waiting for Infinispan CR updates. New events are fired automatically on CR changes.
- removed redundant infinispan cr get at the reconc start.

Please have a look

**Comment by dmvolod** [comment]
> @dmvolod logs looks very clean now, no more update error.
> I've added a commit with some optimizations:
> 
> * removed event requeue if waiting for Infinispan CR updates. New events are fired automatically on CR changes.
> * removed redundant infinispan cr get at the reconc start.
> 
> Please have a look

Cool optimization, @rigazilla, thanks. Looks very good.

**Review by rigazilla — APPROVED** [review]

**Comment by dmvolod** [comment]
Thanks for review and optimization, @rigazilla 
Merged

**Pull request merged**
