### PR TITLE
Persistent volume #126

### PR DESCRIPTION
**Pull request by rigazilla**
Persistent volume implemented here + tests.

### CODE REVIEW

**Comment by galderz** [comment]
@rigazilla Persistent volume information should go under `.spec.service` and should only be used when Data Grid service is used. The design doc has an example of this already:

```
spec:
  image: jboss/infinispan-server:latest
  replicas: 6
  profile: Performance
  service:
    type: Data Grid
    container:
      storage: 2Gi
```

And the [design doc](https://github.com/infinispan/infinispan-operator/blob/master/doc/design.adoc#infinispanservicecontainerspec) already specifies how this should be configured. Any reason to do it in a different way? Or just an oversight?

**Comment by galderz** [comment]
The rest looks good, nice tests :)

**Comment by rigazilla** [comment]
> ```
> 
> ```
> 
> 
> And the [design doc](https://github.com/infinispan/infinispan-operator/blob/master/doc/design.adoc#infinispanservicecontainerspec) already specifies how this should be configured. Any reason to do it in a different way? Or just an oversight?

The need to have persistence (at least for permanent caches) seems quite general, to we really want it to be enable only for Data Grid?

**Comment by galderz** [comment]
> The need to have persistence (at least for permanent caches) seems quite general, do we really want it to be enable only for Data Grid?

We discussed this during the 7.3 development. Cache service does of course need persistence for permanent cache definitions...etc, but this is only for metadata and the persistence size of this should not be configurable by the user. If you look at the 7.3 cache service template, you won't see an option to configure the persistence size, even if we test permanent caches with cache service.

In data grid service, persistence is used for actual cached data and there we do want to have it configurable. In 7.3 data grid service template you'll see an option to configure persistence size.

**Comment by rigazilla** [comment]
> We discussed this during the 7.3 development. Cache service does of course need persistence for permanent cache definitions...etc, but this is only for metadata and the persistence size of this should not be configurable by the user. If you look at the 7.3 cache service template, you won't see an option to configure the persistence size, even if we test permanent caches with cache service.
> 

uhm ok, so your idea is: always create a persistent volume with predefined size for metadata. Right?

**Comment by galderz** [comment]
> uhm ok, so your idea is: always create a persistent volume with predefined size for metadata. Right?

Yeah, for cache service we need that. For now you can just do it by default and that's it. Then, if using datagrid service you just configure the size of it.

**Comment by rigazilla** [comment]
@galderz changed according design.

**Pull request merged**
