### PR TITLE
removed waitForPodsOrFail #750

### PR DESCRIPTION
**Pull request by rigazilla**
Remove duplicate code in test suite

### CODE REVIEW

**Comment by rigazilla** [comment]
@dmvolod @ryanemerson I would like to merge pakages `test/e2e/util` and `test/e2e/utils` in this PR. wdyt?

**Comment by dmvolod** [comment]
Yes, good idea, @rigazilla . `k8s` probably, not `util` or I missed something

**Comment by rigazilla** [comment]
> Yes, good idea, @rigazilla . `k8s` probably, not `util` or I missed something

it's a little mess: the folder is `k8s` but the package is `util`, anyway I'll move everything under `utils`

**Comment by rigazilla** [comment]
I've also removed the test/constants package

**Review by dmvolod — APPROVED** [review]

**Comment by rigazilla** [comment]
merged, thanks!

**Pull request merged**
