### PR TITLE
Added negative test for authentication #101

### PR DESCRIPTION
**Pull request by rigazilla**
Added a test for checking that authentication fails (Unauthorized) if wrong credentials are presented.

### CODE REVIEW

**Comment by galderz** [comment]
Needs rebase

**Comment by rigazilla** [comment]
I'll rebase this after #102 will be merged

**Comment by galderz** [comment]
@rigazilla Needs rebasing again, sorry for delay!

**Comment by rigazilla** [comment]
replaced by #148

**Pull request closed without merging**
