### PR TITLE
fixes issue #1572 config examples

### PR DESCRIPTION
**Pull request by oraNod**
Fixes https://github.com/infinispan/infinispan-operator/issues/1572 and needs backport to 2.2

### CODE REVIEW

**Comment by oraNod** [comment]
@ryanemerson Do you think it's worth expanding the config examples to show another template or possibly a cache?

**Comment by ryanemerson** [comment]
> @ryanemerson Do you think it's worth expanding the config examples to show another template or possibly a cache?

:+1: 

If we can show multiple templates and a cache(s) consuming them I think it will be much clearer to users.

**Comment by oraNod** [comment]
@ryanemerson I've added some expanded examples but I'm going to change it again so we sync the files from the Infinispan repo: https://raw.githubusercontent.com/infinispan/infinispan/main/documentation/src/main/asciidoc/topics/yaml/cache_template_inheritance.yaml

That won't show "my-cache" in the config though.

**Review by ryanemerson — APPROVED** [review]
Great work @oraNod. Can you rebase to a single commit?

**Comment by oraNod** [comment]
> Great work @oraNod. Can you rebase to a single commit?

Done. I guess we'll need to rework the GH action for 2.2 then add this to the Helm repo?

**Comment by oraNod** [comment]
@ryanemerson I updated the commit message. if there's nothing else I'll create the backport for 2.2 after you merge.

**Comment by oraNod** [comment]
@ryanemerson Shall I merge this and backport to 2.2? I can get the Helm docs while I'm at it.

**Comment by ryanemerson** [comment]
Sorry about the delay @oraNod. Backporting would be great, thanks!

**Comment by oraNod** [comment]
@ryanemerson No worries. I'll take care of the backport.

**Pull request merged**
