### PR TITLE
ISPN-10118 ISPN-10126 Minikube and status field fix

### PR DESCRIPTION
**Pull request by galderz**
* Make example CRs runnable with default Minikube settings.
* Add minikube targets to run operator with Minikube.
* Fix status field in operator

### CODE REVIEW

**Comment by galderz** [comment]
Replaces #37

**Comment by galderz** [comment]
Hey @rigazilla, anything wrong with this? Over 1 month waiting to be integrated ;)

**Comment by rigazilla** [comment]
@galderz lgtm. Not a big issue but, since minikube is fully managed via make except for stopping: how about `make minikube-stop`?

**Comment by galderz** [comment]
@rigazilla Makes sense, I'll add that.

**Comment by galderz** [comment]
@rigazilla Added

**Comment by rigazilla** [comment]
thank you @galderz!

**Pull request merged**
