### PR TITLE
Change Grafana CPU Load to CPU Usage

### PR DESCRIPTION
**Pull request by wburns**
Show the CPU usage of the JVM process for the pod instead of the system load average.

### CODE REVIEW

**Comment by dmvolod** [comment]
@wburns please run `make embed-resources` for embedding Grafana json into the code

**Comment by wburns** [comment]
> @wburns please run `make embed-resources` for embedding Grafana json into the code

Ah, thanks. :+1:  Didn't realize we had to commit that in as well.

**Comment by wburns** [comment]
Updated.

**Comment by wburns** [comment]
Fixes https://github.com/infinispan/infinispan-operator/issues/1135

**Review by rigazilla — APPROVED** [review]
lgtm

**Comment by rigazilla** [comment]
merged, thanks @wburns !

**Pull request merged**
