### PR TITLE
Fix attribute issues with ISPN-14185 updates

### PR DESCRIPTION
**Pull request by dfitzmau**
JIRA: https://issues.redhat.com/browse/ISPN-14185

### CODE REVIEW

**Comment by dfitzmau** [comment]
Hi @ryanemerson and @dvagnero . Please review this PR for use of attributes. The original text in https://github.com/infinispan/infinispan-operator/pull/1690 PR contained inconsistencies with some attributes. 

I can merge the PR when I get approvals from you both.

**Comment by dvagnero** [comment]
Lgtm thanks @dfitzmau

**Comment by dfitzmau** [comment]
> Lgtm thanks @dfitzmau

Thanks. You OK to hit that Approval button :) ?

**Review by dvagnero — APPROVED** [review]

**Comment by dfitzmau** [comment]
> Thanks @dfitzmau. FYI we don't use the ISPN issue tracker for this repo, so I have removed from that part from the commit message.

Thanks, @ryanemerson

**Pull request merged**
