### PR TITLE
Ensure genereated credentials are random #1053

### PR DESCRIPTION
**Pull request by ryanemerson**

### CODE REVIEW

**Comment by dmvolod** [comment]
@ryanemerson just for my information: is it means, that before this fix password was the same for the same cluster or I missed something?

**Review by dmvolod — APPROVED** [review]

**Comment by ryanemerson** [comment]
> @ryanemerson just for my information: is it means, that before this fix password was the same for the same cluster or I missed something?

Previously every call to `rand.Int` with the same size arg would cycle through the same numbers, which meant that for each operator deployment the generated passwords would be predictable for a given deployment. For example, the first Infinispan CR cluster to be created by an operator would always have the same credentials, the second cluster created by all operators would have the same credentials.

**Comment by ryanemerson** [comment]
Just repushing to fix a type in the commit message.

**Comment by rigazilla** [comment]
merged thanks @ryanemerson !

**Pull request merged**
