### PR TITLE
Migration to the Operator SDK 0.15.2

### LINKED ISSUE #288: Update code to the latest operator-sdk
Current operator code is based on an skeleton generated by an old operator-sdk. Assess whether is possible to update it.

### PR DESCRIPTION
**Pull request by dmvolod**
Fixes #288

### CODE REVIEW

**Comment by dmvolod** [comment]
@rigazilla thanks for pointing this. Will add this function soon.

**Comment by dmvolod** [comment]
@rigazilla could you please to have a look at this changes.
Thank you.

**Comment by rigazilla** [comment]
Great job @dmvolod! Merged

**Comment by galderz** [comment]
Bravo @dmvolod :)

**Pull request merged**
