### PR TITLE
Change extract from Data section to StringData for tls secret

### PR DESCRIPTION
**Pull request by rigazilla**
1.1.x backport for pr #268

### CODE REVIEW

**Comment by dmvolod** [comment]
I'm sorry, @rigazilla . I've tested more deeply this issue and this PR and commit to the master should be reverted.

**Comment by rigazilla** [comment]
> I'm sorry, @rigazilla . I've tested more deeply this issue and this PR and commit to the master should be reverted. I will change the unit-test according this issue. Thanks a lot.

no worries, what's the problem?

**Comment by dmvolod** [comment]
The problem was in FakeClient implementation which is using for unit-test as it place and store both Data and StringData fields "as is", but in real k8s and OpenShift StringData is write only fields and can't be use for reading. I will think how to write test for this issue to prevent problem like this.

**Comment by dmvolod** [comment]
@rigazilla , let's close this PR as I send revert for the commit

**Pull request closed without merging**
