### PR TITLE
Send event to console #346

### LINKED ISSUE #346: Send user related warnings to the console Events log

### PR DESCRIPTION
**Pull request by rigazilla**
Fixes #346 
replaces #1008

### CODE REVIEW

**Review by ryanemerson — APPROVED** [review]
Much simpler this way :slightly_smiling_face:

**Comment by dmvolod** [comment]
@rigazilla please update required access rights

**Comment by rigazilla** [comment]
> @rigazilla please update required access rights

right
> Otherwise looks very simple and good

 thanks @dmvolod

**Review by dmvolod — APPROVED** [review]

**Comment by dmvolod** [comment]
@rigazilla sse,s to we are ready to merge this PR, please rebase and squash commits

**Comment by rigazilla** [comment]
@dmvolod rebased and squashed, thanks!

**Comment by ryanemerson** [comment]
@rigazilla CI is failing as it's not compiling.

**Comment by rigazilla** [comment]
ops, sorry guys. Should be better now

**Comment by dmvolod** [comment]
Thanks, @rigazilla 
Merged into master

**Pull request merged**
