### PR TITLE
Changed jvmOptionAppend to extraJvmOpts

### PR DESCRIPTION
**Pull request by rigazilla**
Changed jvmOptionAppend to extraJvmOpts

### CODE REVIEW

**Comment by galderz** [comment]
Needs rebasing after Infinispan 10 upgrade

**Comment by rigazilla** [comment]
@galderz no need for this on master. Moved on 0.x branch

**Comment by galderz** [comment]
@rigazilla Actually, we only want it for master. We won't rename any other config options in 0.x branch any more.

**Comment by rigazilla** [comment]
This PR cannot be moved to master, closing. Opened #139

**Pull request closed without merging**
