### PR TITLE
Readd CreateOrPatch port

### PR DESCRIPTION
**Pull request by ryanemerson**

### CODE REVIEW

**Comment by gustavonalle** [comment]
It still throws an error, but it moves past the shutdown and is able to recreate the pod

**Comment by gustavonalle** [comment]
```
2021-10-05T17:38:22.348+0100    INFO    controllers.Infinispan  StatefulSet.Spec.Replicas!=0    {"Request.Namespace": "default", "Request.Name": "demo-cluster"}
2021-10-05T17:38:22.348+0100    INFO    controllers.Infinispan  Waiting that all the pods become unready        {"Request.Namespace": "default", "Request.Name": "demo-cluster"}
2021-10-05T17:38:22.361+0100    ERROR   controllers.Infinispan  failed to update StatefulSet    {"Request.Namespace": "default", "Request.Name": "demo-cluster", "StatefulSet.Name": "demo-cluster", "error": "Operation cannot be fulfilled on statefulsets.apps \"demo-cluster\": the object has been modified; please apply your changes to the latest version and try again"}
github.com/go-logr/zapr.(*zapLogger).Error
        /home/gfernandes/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
github.com/infinispan/infinispan-operator/controllers.(*infinispanRequest).reconcileGracefulShutdown
        /home/gfernandes/github/infinispan-operator/controllers/infinispan_controller.go:1238
github.com/infinispan/infinispan-operator/controllers.(*InfinispanReconciler).Reconcile
        /home/gfernandes/github/infinispan-operator/controllers/infinispan_controller.go:394
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /home/gfernandes/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:263
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /home/gfernandes/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:235
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1
        /home/gfernandes/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:198
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1
        /home/gfernandes/go/pkg/mod/k8s.io/apimachinery@v0.19.4/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
        /home/gfernandes/go/pkg/mod/k8s.io/apimachinery@v0.19.4/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
        /home/gfernandes/go/pkg/mod/k8s.io/apimachinery@v0.19.4/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
        /home/gfernandes/go/pkg/mod/k8s.io/apimachinery@v0.19.4/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext
        /home/gfernandes/go/pkg/mod/k8s.io/apimachinery@v0.19.4/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.UntilWithContext
        /home/gfernandes/go/pkg/mod/k8s.io/apimachinery@v0.19.4/pkg/util/wait/wait.go:99
2021-10-05T17:38:22.362+0100    INFO    controllers.Infinispan  ----- End Reconciling Infinispan.       {"Request.Namespace": "default", "Request.Name": "demo-cluster"}
2021-10-05T17:38:22.362+0100    ERROR   controller-runtime.manager.controller.infinispan        Reconciler error        {"reconciler group": "infinispan.org", "reconciler kind": "Infinispan", "name": "demo-cluster", "namespace": "default", "error": "Operation cannot be fulfilled on statefulsets.apps \"demo-cluster\": the object has been modified; please apply your changes to the latest version and try again"}
github.com/go-logr/zapr.(*zapLogger).Error
```

**Comment by dmvolod** [comment]
> Operation cannot be fulfilled on statefulsets.apps \"demo-cluster\": the object has been modified; please apply your changes to the latest version and try again"

This error could be ignored with code like
``` go
if errors.IsConflict(err) {
	return reconcile.Result{Requeue: true}, nil
}
```

**Comment by gustavonalle** [comment]
Is it ok to ignore though? It seems the controller is failing to change the state of the statefulset

**Comment by dmvolod** [comment]
> Is it ok to ignore though? It seems the controller is failing to change the state of the statefulset, or is changing it twice with different states

seems to controller fails to update StatefulSet with 0 replicas. I think it should be ignored and can be re-submitted as it's a typical problem with Update
``` go
statefulSet.Spec.Replicas = pointer.Int32Ptr(0)
```

**Comment by ryanemerson** [comment]
It's true this kind of error is seen the logs of other operators. I think we should try @dmvolod  suggestion for now and investigate more later as this is a blocking issue atm and we have plenty of other PRs to get in before release.

**Pull request merged**
