### PR TITLE
Switch to operator version 2.2 in docs

### PR DESCRIPTION
**Pull request by dmvolod**
I'm not sure about correct version for Operator and Infinispan server

### CODE REVIEW

**Comment by oraNod** [comment]
@dmvolod thanks for updating this for the branching. I pushed a commit to this branch and opened a PR to update the attributes for 2.1.x.

**Review by oraNod — CHANGES_REQUESTED** [review]
Operator 2.2 to Infinispan 13.0

**Comment by dmvolod** [comment]
> thanks for updating this for the branching. I pushed a commit to this branch and opened a PR to update the attributes for 2.1.x.

Thanks, @oraNod , commit squashed

**Review by oraNod — APPROVED** [review]

**Comment by oraNod** [comment]
thanks @dmvolod

**Pull request merged**
