### PR TITLE
Package Restructure

### PR DESCRIPTION
**Pull request by ryanemerson**
https://github.com/infinispan/infinispan-operator/issues/568

```
pkg
├── apis
│   ├── addtoscheme_infinispan_v1.go
│   ├── addtoscheme_infinispan_v2alpha1.go
│   ├── apis.go
│   └── infinispan
│       ├── group.go
│       ├── v1
│       │   ├── doc.go
│       │   ├── infinispan_types.go
│       │   ├── register.go
│       │   ├── types_util.go
│       │   ├── zz_generated.deepcopy.go
│       │   └── zz_generated.openapi.go
│       └── v2alpha1
│           ├── cache_types.go
│           ├── doc.go
│           ├── register.go
│           ├── types_util.go
│           ├── zz_generated.deepcopy.go
│           └── zz_generated.openapi.go
├── controller
│   ├── add_cache.go
│   ├── add_infinispan.go
│   ├── cache
│   │   └── cache_controller.go
│   ├── constants
│   │   └── constants.go
│   ├── controller.go
│   └── infinispan
│       ├── autoscale.go
│       ├── infinispan_controller_fake.go
│       ├── infinispan_controller.go
│       ├── infinispan_controller_test.go
│       ├── service_site.go
│       └── xsite.go
├── infinispan
│   ├── caches
│   │   └── caches.go
│   ├── client
│   │   └── http
│   │       ├── client.go
│   │       └── curl
│   │           └── curl.go
│   ├── cluster.go
│   ├── configuration
│   │   └── configuration.go
│   └── security
│       └── users.go
├── kubernetes
│   ├── kubernetes.go
│   └── pods.go
└── launcher
    ├── launcher.go
    └── main.go

```

### CODE REVIEW

**Review by dmvolod — APPROVED** [review]

**Comment by dmvolod** [comment]
@ryanemerson , @rigazilla let's merge this PR first, to prevent regular rebase on each merged functional PR

**Comment by ryanemerson** [comment]
That would be very helpful for the other PRs I have coming :slightly_smiling_face: 

I have just pushed an updates to remove the final utils package `pkg/controller/utils/cache/default.go -> pkg/infinispan/caches/caches.go`, but I don't envisage any other changes on this PR unless requested.

**Comment by rigazilla** [comment]
ok, merged! Thanks @ryanemerson !

**Comment by dmvolod** [comment]
Oh, @ryanemerson I'm missing that you moved some common things, i.e. `LabelsResource`, `contains`, `PodLabels`, etc. inside the infinispan_controller.go but they are not only this controller related. Maybe move them out?

**Comment by ryanemerson** [comment]
I moved `LabelsResource` and `PodLabels` into the controller as they are specific to infinispan controller resources due to the presence of the "infinispan_cr" label. Where these are required outside the infinispan controller, e.g. cache_controller, they can be accessed via `ispnctrl.LabelsResource`. This makes it explicit that the cache_controller has a dependency on the infinispan controller logic.

The `contains` and `remove` methods are obviously very generic, however as they're currently not required anywhere else in the code I did not want to prematurely introduce a package to just contain those methods. I figured we can add this if/when that functionality is required elsewhere in the code. Similarly, I also wanted to avoid reintroducing another "util" package that everything gets dumped in.

**Comment by dmvolod** [comment]
Ok, good,  agreed.

**Pull request merged**
