### PR TITLE
Utilise Ephemeral storage in testsuite #1433

### PR DESCRIPTION
**Pull request by ryanemerson**

### CODE REVIEW

**Comment by Crumby** [comment]
I would say that `TestPodDegradationAfterOOM` and `TestNodeWithStorageClass` should have ephemeral set to `false` too

**Comment by Crumby** [comment]
@ryanemerson I wondering whether some of the "field update" tests should have ephemeral storage set to true. They are effectively restarting the pods or whole cluster with different configuration. Question is whether the update change somehow affects anything that is stored on the persistent storage.

Eg. `TestCPUUpdateWithTwoReplicas` uses two replicas only because there was an issue with global state file in the initial release and updating CPU caused some issue when the pods started cycling through update.

**Comment by Crumby** [comment]
Cross site tests could leverage ephemeral storage too. No need to have PVs for the tests we currently have

**Comment by ryanemerson** [comment]
> @ryanemerson I wondering whether some of the "field update" tests should have ephemeral storage set to true. They are effectively restarting the pods or whole cluster with different configuration. Question is whether the update change somehow affects anything that is stored on the persistent storage.

I think `TestContainerCPUUpdateWithTwoReplicas` is the only update test that doesn't use the default spec, so is the only update test I'm aware of that doesn't have Ephemeral storage.

> Eg. `TestCPUUpdateWithTwoReplicas` uses two replicas only because there was an issue with global state file in the initial release and updating CPU caused some issue when the pods started cycling through update.

I think it would be good to keep `TestCPUUpdateWithTwoReplicas` with actual storage so we have some coverage for StatefulSet in place pod updates with global state.

**Comment by ryanemerson** [comment]
> Cross site tests could leverage ephemeral storage too. No need to have PVs for the tests we currently have

It seems they already are :slightly_smiling_face:

**Comment by ryanemerson** [comment]
The results aren't dramatic, but we seemed to have shaven a few minutes of the total testsuite time.

**Pull request merged**
