### PR TITLE
Revert "Revisit CreateOrUpdate usage (separate Spec and Status.Conditions updates)

### PR DESCRIPTION
**Pull request by dmvolod**

### CODE REVIEW

**Comment by ryanemerson** [comment]
@dmvolod Do we need your changes in https://github.com/kubernetes-sigs/controller-runtime/pull/1403/files porting to our `controllerutil` before we can merge this?

**Comment by dmvolod** [comment]
Yes, sure, @ryanemerson sorry, but I didn't know about release, we need to wait until controller-runtime PR will be merged and than we can bump commit to the local package

**Comment by ryanemerson** [comment]
> @dmvolod Do we need your changes in https://github.com/kubernetes-sigs/controller-runtime/pull/1403/files porting to our `controllerutil` before we can merge this?

@dmvolod Sorry if it wasn't clear. What I meant was can we just port the changes from your PR to our local `controllerutil` as part of this PR so that the status & spec are updated?

**Comment by dmvolod** [comment]
> Sorry if it wasn't clear. What I meant was can we just port the changes from your PR to our local `controllerutil` as part of this PR so that the status & spec are updated?

Sorry, @ryanemerson I thought that controller-runtime PR will be merged soon, and we can easy to revert this commit and do quick bump from this repo, but it still waiting to be merge, however targeted to some milestone.
Seem to we can add to this commit part of the controller-runtime fix. Will do this.
Thanks for taking care.

**Comment by ryanemerson** [comment]
Thanks @dmvolod

**Pull request merged**
