### PR TITLE
Remove CR1 image binding in test

### PR DESCRIPTION
**Pull request by dmvolod**
This was introduced in #727

### CODE REVIEW

**Comment by ryanemerson** [comment]
Good spot @dmvolod. My mistake!

**Review by ryanemerson — APPROVED** [review]

**Comment by dmvolod** [comment]
Ops, something going wrong with the latest image.
`Unexpected response code 400` in test

**Comment by dmvolod** [comment]
@ryanemerson do you have an idea, why sometimes cache create via REST fails with HTTP 400 code

**Comment by ryanemerson** [comment]
@dmvolod The 400 on the CI logs is very strange. The error is being thrown by the backup/restore tests, however those tests do not use the `DefaultSpec` var in `main_test.go` so they shouldn't be related.

I have pulled your change locally and I'm unable to reproduce.

**Comment by dmvolod** [comment]
Thanks, @ryanemerson 
I will close this PR as also removed CR1 in #781 which never failed
Sims to be a problem with CI

**Pull request closed without merging**
