### PR TITLE
Remove TestCacheServiceNativeImage test

### PR DESCRIPTION
**Pull request by dmvolod**

### CODE REVIEW

**Review by Crumby — APPROVED** [review]

**Comment by ryanemerson** [comment]
@dmvolod I think if we're going to keep this test, then by default it should be enabled on the upstream CI, otherwise it will always be ignored and we might as well remove the test. So I think we need to set the env in the travis file.

**Comment by Crumby** [comment]
@ryanemerson What about removing the test and running the whole testsuite with the native server image as discussed on Zulip? Or is that out of scope for now?

**Comment by ryanemerson** [comment]
@Crumby It would be cool to have, however I think a lot of tests would be broken at this stage. I think given the low priority of the native server at this time it would be better to focus our efforts elsewhere.

**Comment by Crumby** [comment]
@ryanemerson Does it makes sense to have the test present at all at this moment? I mean from your statement it seems it's not usable by users and there is a lot of work to be done before it'll be working. It's using Cache service which is intended to be abandoned. Running the test takes CI time with each PR

**Comment by ryanemerson** [comment]
Good point @Crumby. I would be happy to remove the test altogether.

**Comment by dmvolod** [comment]
@Crumby , @ryanemerson are you decide to remove all TestCacheService* from the test suite?
In this case I will close this PR and create a new to remove them at all.

**Comment by Crumby** [comment]
@dmvolod I meant specifically `TestCacheServiceNativeImage` as that's the only tests using native server image.

**Comment by dmvolod** [comment]
> I meant specifically `TestCacheServiceNativeImage` as that's the only tests using native server image.

Yes, true, @Crumby . Current changes disables `TestCacheServiceNativeImage` both for CI and default test in separate cluster

**Comment by ryanemerson** [comment]
> @dmvolod I meant specifically `TestCacheServiceNativeImage` as that's the only tests using native server image.

+1 to only removing the Native test.

**Review by Crumby — APPROVED** [review]

**Comment by ryanemerson** [comment]
Thanks @dmvolod

**Pull request merged**
