### PR TITLE
[2.0.x] Tests TestContainer<Memory | CPU | JavaOpts>Update could raise "object has been modified" exception

### PR DESCRIPTION
**Pull request by dmvolod**

### CODE REVIEW

**Comment by Crumby** [comment]
@dmvolod It seems to affect also `TestPernamentCache` and all other using it's common code. But in this case it doesn't seem to affect test result. (It probably doesn't restart the cluster as it should since that's main point of the test):

```
=== RUN   TestPermanentCache
Create cache: https://ac18e0f6864944466b08a99b900041ad-2008877968.eu-north-1.elb.amazonaws.com:11222/rest/v2/caches/test
Error updating infinispan Operation cannot be fulfilled on infinispans.infinispan.org "test-permanent-cache": the object has been modified; please apply your changes to the latest version and try again
Put request via route: &{POST https://ac18e0f6864944466b08a99b900041ad-2008877968.eu-north-1.elb.amazonaws.com:11222/rest/v2/caches/test/test HTTP/1.1 1 1 map[Authorization:[Basic ZGV2ZWxvcGVyOmhEakMzZ2gzQ0EyRzRpa20=] Content-Type:[text/plain]] {test-operator} 0x82bc80 13 [] false ac18e0f6864944466b08a99b900041ad-2008877968.eu-north-1.elb.amazonaws.com:11222 map[] map[] <nil> map[]   <nil> <nil> <nil> 0xc0000400f0}
Delete cache: https://ac18e0f6864944466b08a99b900041ad-2008877968.eu-north-1.elb.amazonaws.com:11222/rest/v2/caches/test
--- PASS: TestPermanentCache (384.65s)
```

**Comment by dmvolod** [comment]
Yes, correct, @Crumby 
All updates including genericTestForGracefulShutdown need to be fixed
Never seen this error in the master
Probably this is side effect of the #763

**Comment by dmvolod** [comment]
@Crumby created #830 to fix others Infinspan CR update issues

**Review by rigazilla — APPROVED** [review]
lgtm

**Review by Crumby — APPROVED** [review]

**Comment by rigazilla** [comment]
merged thanks @dmvolod !

**Pull request merged**
