### PR TITLE
Use TLSv1.3 as default for Cross Site

### PR DESCRIPTION
**Pull request by pruivo**

### CODE REVIEW

**Comment by pruivo** [comment]
> Can't we just set `TLS` and let the handshake figure the best ?

Sure; I had the idea that we want to force TLS 1.3 everywhere.
If both the server and gossip-router support TLS 1.2 and TLS 1.3, which version will the protocol choose?

**Comment by pruivo** [comment]
keeping this on hold until we have a server image with [JGRP-2638](https://issues.redhat.com/browse/JGRP-2638)

**Comment by ryanemerson** [comment]
@pruivo Is this included in 14.0.0.Final?

**Comment by pruivo** [comment]
@ryanemerson no, it isn't. Part of the fix is in JGroups code and we didn't upgrade yet.

**Comment by ryanemerson** [comment]
Thanks for the update. Just let me know when the time is right :+1:

**Pull request merged**
